### DISCUSSION TITLE
Automatic solar reduction during negative export pricing

### DISCUSSION THREAD

**Discussion by herbi3** [amberelectric/public-api#123] [Show and tell]
Getting charged to export to the grid isn't quite ideal, especially when there is no control over what the inverter is doing.

Luckily, Solaredge inverters support TCP Modbus, and I am able to send the command to the inverter to ZERO export (solar production matches consumption only) this helps the grid reduce its surplus requirements and I also don't get charged to export.

This setup, I run a ubuntu virtual machine, using [emoncms](https://github.com/emoncms/emoncms/blob/master/docs/LinuxInstall.md) as a service, a custom script to pull pricing from amber API, and another custom script that polls both solaredge inverters and pulls data from all of the registers (production, consumption, export etc.)

All of the data is posted into InfluxDB via telegraph (mqtt plugin, connecting to the emoncms mqtt as its source) - within emoncms after setting up each feed, I have each one then publish to its own mqtt server, which telegraph picks up and ships it to the influx database. Then visualised with Grafana.

If anyone else has the same inverters and meter attached, I am more than happy to help duplicate this setup. you'll need your own amber api key, hardware etc. Solaredge TCP modbus is now available for setapp enabled inverters, over secured WiFi, it just needs to be enabled by directly connecting to the inverter.

[Here is the automated dashboard, there are x3 publicly available - just select different ones from the top left of the page](https://public.winterfell.tv/grafana/d/ScuNHcx7k/public-electricity-consumption-analysis?orgId=1&refresh=1m&from=now-24h&to=now)

![Screen Shot 2022-10-14 at 11 49 49 am](https://user-images.githubusercontent.com/11141749/195743591-f372cce5-6458-415b-8aa1-51be56a7c44e.png)
![Screen Shot 2022-10-14 at 11 49 59 am](https://user-images.githubusercontent.com/11141749/195743601-f75e9820-1793-4918-9d76-3543249870e3.png)

**Comment by tjc998** [comment]
Looks very cool. Modbus does seem to be a much more responsive way of getting data than by polling their API. 
Do you have a link to the modbus register map?

**Reply by herbi3** [reply]
The result is instant, as the amber api is polled every 10s or so to get the real-time price

I’m using this great tool by nmakel here

https://github.com/nmakel/solaredge_modbus

Writing data to some registers is still be worked on

**Comment by purcell-lab** [comment]
I'm very interested in this functionality as well.

I originally enrolled my solar inverters in SmartShit with the hope that Amber could automate the zero export. Unfortunately the SmartShift solution ended up resetting the SolarEdge inverters and not switching to zero export so Amber had to switch off that functionality and have a firmware fix underdevelopment with SolarEdge.

In the meantime I have been trying to setup zero export locally via SetApp, but every time I change my export values they switch back to defaults after 30 seconds. SolarEdge support have said this is because my inverters are enrolled in (Grid Services) external control via SmartShift. So I'm in the process of un-enrolling my solar inverters from SmartShift so I can enable local control of zero export. Note, my battery (Powerwall2) remains enrolled in SmartShift because that is working well.

With SolarEdge inverters there is also the need to change the AdvancedPwrControlEn register to on, which I presume I could do with a ModBus call as I don't seem to be able to do that with SetApp.

**Reply by herbi3** [reply]
That’s a good point, I found when reading the `AdvancedPwrControlEn` via modbus, it was already enabled on both of my 10kwh threephase inverters (follower was probably set from the master inverter). I haven’t yet been successful in changing that status via modbus just yet - the reading of that register seems to be different when writing back to the register.

**Reply by wh0phd** [reply]
2 weeks later — did you have any luck @herbi3 ?

**Reply by herbi3** [reply]
@wh0phd - not yet, since it’s already enabled this setting for me so far at least, won’t be needed to change often. It can be changed anyway via going directly through the inverter web gui too, so it’s not essential to be included (yet)

**Reply by wh0phd** [reply]
I just had a look around the web GUI — sorry where is this setting to change?

**Reply by herbi3** [reply]
@wh0phd - it was already enabled when RRCR was changed (that’s what I noticed at least). What does the register say when you read the data from the inverter? Was yours already enabled by default  too?

**Comment by tux43** [comment]
I’ve done something very similar after being a customer for about a month. I have skills with Home Automation and have managed to do a few things that you might find interesting. 

My setup:-
- 7.8kW of Solar Panels with 6kW inverter
- Electric Vehicle
- No battery (yet!)

Functionality achieved:-
- When solar feed-in tariff is negative spin down the inverter to only cover household demand (TCP/IP connected modbus inverter required)
- Maximise Electric Vehicle charging by using only surplus solar power when the feed in tariff is negative
- Spin down the inverter to 0W output when power prices go negative plus activate high load appliances such as EV charging, Air Conditioner, Hot Water, Flood Lights, Pool Pump etc…
- Turn off appliances when prices surge above $1kW/h, reenabling after surge has subsided 
- Set your own off-peak & peak thresholds so dishwasher, washing machines etc… run during favourable times
- [Battery could be discharged to the grid when price hit a threshold. I haven’t tested this however relatively easy.]

<img width="1355" alt="Screen Shot 2022-10-22 at 10 23 22 am" src="https://user-images.githubusercontent.com/53364421/197306306-b4ab8662-9ae0-482a-ac3b-8ef3b8dd13bd.png">

**Reply by purcell-lab** [reply]
> I have skills with Home Automation and have managed to do a few things that you might find interesting

I would be very interested so see how you have implemented these automations, can you share your automation scripts?

Here are my automations in Home Assistant:

https://community.home-assistant.io/t/running-devices-when-energy-is-cheaper-and-greener/380011?u=markpurcell

**Reply by tux43** [reply]
Sure, I did a bit of a writeup here - https://community.home-assistant.io/t/automate-fronius-soft-limit/465124/6 I am happy to share anything that might be missing.

**Reply by tux43** [reply]
> I’ve done something very similar after being a customer for about a month. I have skills with Home Automation and have managed to do a few things that you might find interesting.

Update: I've had a couple of days where this worked very favourably, allowing me to charge EV during times where power cost was <= $0! 

You will see in the below graphs that the majority of my usage was when cost is $0. This makes Amber great!!

<img width="795" alt="Screenshot 2022-10-29 at 8 05 39 am" src="https://user-images.githubusercontent.com/53364421/198737700-60c794c9-7e36-4c86-99ec-9e7ecc3ffe10.png">

<img width="781" alt="Screenshot 2022-10-29 at 8 08 24 am" src="https://user-images.githubusercontent.com/53364421/198737708-46eaf47a-9de8-4405-9517-232fb616cc08.png">

**Comment by purcell-lab** [comment]
I managed this for the first time this week.

Set my solar inverters to zero export and it curtailed my solar production to meet my household load.

![Screenshot_20221104-212444](https://user-images.githubusercontent.com/79175134/200097760-5d84bd82-a4ea-44ef-9f54-a7c077ec5fde.png)

**Reply by purcell-lab** [reply]
Here is my Home Assistant automation.

```yaml
alias: Zero Export Automation
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.amber_feed_in_price
    below: 0
  - platform: numeric_state
    entity_id: sensor.amber_feed_in_price
    above: 0
  - platform: numeric_state
    entity_id: sensor.amber_general_price
    above: 0
  - platform: numeric_state
    entity_id: sensor.amber_general_price
    below: 0
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.amber_feed_in_price
            below: 0
          - condition: numeric_state
            entity_id: sensor.amber_general_price
            above: 0
        sequence:
          - device_id: 8e8f45345219e32b8a645ce8dfb767c3
            domain: select
            entity_id: select.solaredge_i1_limit_control_mode
            type: select_option
            option: Export Control (Export/Import Meter)
          - device_id: 8e8f45345219e32b8a645ce8dfb767c3
            domain: number
            entity_id: number.solaredge_i1_site_limit
            type: set_value
            value: 200
      - conditions:
          - condition: numeric_state
            entity_id: sensor.amber_general_price
            below: 0
        sequence:
          - device_id: 8e8f45345219e32b8a645ce8dfb767c3
            domain: select
            entity_id: select.solaredge_i1_limit_control_mode
            type: select_option
            option: Production Control
          - device_id: 8e8f45345219e32b8a645ce8dfb767c3
            domain: number
            entity_id: number.solaredge_i1_site_limit
            type: set_value
            value: 0
    default:
      - device_id: 8e8f45345219e32b8a645ce8dfb767c3
        domain: select
        entity_id: select.solaredge_i1_limit_control_mode
        type: select_option
        option: Disabled
mode: single
```
