### DISCUSSION TITLE
Displaying prices in c/kWh instead of $/kWh

### DISCUSSION THREAD

**Discussion by Tuttle13** [amberelectric/public-api#75] [General]
Hi, thanks for the official repo, my question is how does one “go back” to displaying prices (current, forecast etc) in c/kWh instead of $/kWh?

For example, currently it shows the price is $0.1, which I believe could be somewhere between 5.01c and 14.99c. This is a pretty wide range (especially in the next price range of $0.2).

Is there a simple way to display prices either in cents, or at least to two decimal places if it stays in dollars? (And on that, my previous automations triggered at certain c/kWh - is the “behind the scenes price” being outputted at more decimal places, or rounded to a single one as shown? ie could I still have an automation that triggers at $0.17 (17c) or is that second decimal ignored?)

A switch/option to change between c/kWh and $/kWh would be most appreciated. Cheers

**Comment by madpilot** [comment]
> For example, currently it shows the price is $0.1, which I believe could be somewhere between 5.01c and 14.99c

No, that means 10c. The rounding happens before the price gets converted to dollars. If it was 11c, the sensor would show 0.11.

Regardless, we won't be able to offer a switch, unfortunately - it won't pass code review in core. You can use templates to convert the prices if you really want it in c/kWh

Something like

```yaml
template:
  - sensor:
    - name: "General price (c/kWh)"
      unit_of_measurement: "c/kWh"
      state: >
        {{ (states('sensor.amber_general_price')) | float * 100 }}
```

(Replace `sensor.amber_general_price` with whatever you called it)
